In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import matplotlib.gridspec as gridspec
import warnings

warnings.filterwarnings("ignore")

In [2]:
# Carregamento dos dados
df_bruto = pd.read_csv(r'../data/raw/dados_dengue_clima_saneamento_2014_2025.csv')

In [3]:
df_bruto.head()

,Quantidade de Casos,COD_UF,periodo,precipitacao_media_mensal_uf,temp_max_media_mensal_uf,temp_min_media_mensal_uf,umidade_max_media_mensal_uf,umidade_min_media_mensal_uf,pressao_max_media_mensal_uf,pressao_min_media_mensal_uf,Densidade demográfica (pessoas por km²) (Pessoas por km²) (IBGE),"Despesas per capita das famílias com saneamento, em R$ a preços de 2024 (deflator IPCA, item água e esgoto) (R$ per capita a preços de 2024) (SINISA)",Internações por doenças associadas à falta de saneamento (Número de internações) (DATASUS),Número de pessoas por moradia (pessoas por moradia) (IBGE),Número de pessoas por moradia (área urbana) (pessoas por moradia) (IBGE),Parcela da população total que mora em domicílios sem acesso ao serviço de coleta de esgoto (% da população) (SINISA),Parcela da população total que mora em domicílios sem acesso à água tratada (% da população) (SINISA),População total (pessoas) (IBGE),População urbana total (pessoas) (SINISA),Taxa de incidência de internações por doenças associadas à falta de saneamento (Internações por 10 mil habitantes) (DATASUS)
0,521,AC,2014-01,306.200000,26.168398,25.172873,86.335013,80.105127,988.055018,987.365278,4.81,141.07,3459.0,3.65,3.49,8.8,55.4,790101.0,572554.0,43.779
1,860,AL,2014-01,31.033333,27.146483,25.862634,73.222670,67.688172,1000.114113,999.650627,119.28,193.66,7149.0,3.39,3.13,77.7,22.1,3321730.0,2316270.0,21.522
2,1537,AM,2014-01,243.305882,26.704184,25.695380,84.414789,79.235912,1003.842685,1003.189520,2.48,209.39,5485.0,4.06,3.18,9.3,26.1,3873743.0,2540454.0,14.159
3,34,AP,2014-01,320.200000,25.811156,24.882997,87.120968,84.208333,1010.215188,1009.659610,5.26,126.56,1031.0,4.03,4.02,96.1,65.6,750912.0,672809.0,1.373
4,1429,BA,2014-01,48.005405,26.084308,24.723933,73.336720,66.922169,970.333907,969.846090,26.79,350.81,43377.0,3.23,0.31,67.2,21.4,15126371.0,10770479.0,28.676

In [4]:
# Criação do DataFrame de série temporal
df_ts = df_bruto[['periodo', 'Quantidade de Casos', 'COD_UF']].copy()

In [ ]:
print('Informações básicas do DataFrame\n')
df_ts.info()

print('Verificando o Conteúdo do DataFrame\n')
df_ts.head()

Informações básicas do DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3584 entries, 0 to 3583
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   periodo              3584 non-null   object
 1   Quantidade de Casos  3584 non-null   int64
 2   COD_UF               3584 non-null   object
dtypes: int64(1), object(2)
memory usage: 84.1+ KB
Verificando o Conteúdo do DataFrame

   periodo  Quantidade de Casos COD_UF
0  2014-01                  521     AC
1  2014-01                  860     AL
2  2014-01                 1537     AM
3  2014-01                   34     AP
4  2014-01                 1429     BA

In [10]:
print('Verificando valores ausentes\n')
df_ts.isna().sum()

Verificando valores ausentes

periodo                0
Quantidade de Casos    0
COD_UF                 0
dtype: int64

In [11]:
# Renomeando colunas para facilitar o uso com modelos de séries temporais
df_ts.rename(columns={'Quantidade de Casos': 'y', 'COD_UF': 'estado'}, inplace=True)

# Convertendo a coluna 'periodo' para o tipo datetime e depois para Period
df_ts['periodo'] = pd.to_datetime(df_ts['periodo'], format='%Y-%m').dt.to_period('M')

df_ts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3584 entries, 0 to 3583
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   periodo  3584 non-null   period[M]
 1   y        3584 non-null   int64
 2   estado   3584 non-null   object
dtypes: int64(1), object(1), period[M](1)
memory usage: 84.1+ KB

In [ ]:
# Salvar o dataframe df_ts em um arquivo CSV
caminho_salvar = r'../data/raw/dataset_serie_temporal.csv'
df_ts.to_csv(caminho_salvar, index=False)
print(f"DataFrame df_ts salvo com sucesso em: {caminho_salvar}")

DataFrame df_ts salvo com sucesso em: ../data/processed/dataset_serie_temporal.csv